[[sound_effects]]
file_path = "./src/static/sounds/konami.wav"
name = "Konami"
on_open = false
on_close = false

[[sound_effects]]
file_path = "./src/static/sounds/mario-tunnel.wav"
name = "Mario Tunnel"
on_open = false
on_close = false

[[sound_effects]]
file_path = "./src/static/sounds/capcom.wav"
name = "Capcom"
on_open = false
on_close = false

[[sound_effects]]
file_path = "./src/static/sounds/famima.wav"
name = "Famima!"
on_open = false
on_close = false

[[sound_effects]]
file_path = "./src/static/sounds/minecraft-close.wav"
name = "Minecraft Close"
on_open = false
on_close = false

[[sound_effects]]
file_path = "./src/static/sounds/minecraft-open.wav"
name = "Minecraft Open"
on_open = false
on_close = false

[[sound_effects]]
file_path = "./src/static/sounds/zelda-solve.wav"
name = "Zelda Solve"
on_open = false
on_close = false

